<a href="https://colab.research.google.com/github/PawanKalyanJada/NER/blob/main/Name_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
f=open('/content/contentgrive/MyDrive/sentences.txt') 

In [ ]:
l=(f.readlines())

In [ ]:
l[59]

'Critics of Halliburton include auditors and congressional Democrats .\n'

In [ ]:
f1=open('/content/contentgrive/MyDrive/labels.txt')
l1=f1.readlines()

In [ ]:
l1[59]

'O O B-org O O O O O O\n'

In [ ]:
d={'O': 0, 'B-geo': 1, 'B-gpe': 2, 'B-per': 3, 'I-geo': 4, 'B-org': 5, 'I-org': 6, 'B-tim': 7, 'B-art': 8, 'I-art': 9, 'I-per': 10, 'I-gpe': 11, 'I-tim': 12, 'B-nat': 13, 'B-eve': 14, 'I-eve': 15, 'I-nat': 16}

In [ ]:
for i in d:
  d[i]+=1

In [ ]:
d

{'B-art': 9,
 'B-eve': 15,
 'B-geo': 2,
 'B-gpe': 3,
 'B-nat': 14,
 'B-org': 6,
 'B-per': 4,
 'B-tim': 8,
 'I-art': 10,
 'I-eve': 16,
 'I-geo': 5,
 'I-gpe': 12,
 'I-nat': 17,
 'I-org': 7,
 'I-per': 11,
 'I-tim': 13,
 'O': 1}

In [ ]:
c=0
for i in l:
  if(i.startswith('The 41st')):
    print(c)
    break
  c+=1

310


In [ ]:
(l[4].split())

['the',
 'protest',
 'comes',
 'on',
 'the',
 'eve',
 'of',
 'the',
 'annual',
 'conference',
 'of',
 'britain',
 "'s",
 'ruling',
 'labor',
 'party',
 'in',
 'the',
 'southern',
 'english',
 'seaside',
 'resort',
 'of',
 'brighton',
 '.']

In [ ]:
(l1[4].split())

['o',
 'o',
 'o',
 'o',
 'o',
 'o',
 'o',
 'o',
 'o',
 'o',
 'o',
 'b-geo',
 'o',
 'o',
 'b-org',
 'i-org',
 'o',
 'o',
 'o',
 'b-gpe',
 'o',
 'o',
 'o',
 'b-geo',
 'o']

In [ ]:
for i in range(len(l)):
  l[i]=l[i].lower()
for i in range(len(l1)):
  l1[i]=l1[i].lower()

In [ ]:
v={}
c=2
for i in range(len(l)):
  p=l[i].split()
  for j in p:
    if(not(j in v)):
      v[j]=c
      c+=1

In [ ]:
v

{'thousands': 2,
 'of': 3,
 'demonstrators': 4,
 'have': 5,
 'marched': 6,
 'through': 7,
 'london': 8,
 'to': 9,
 'protest': 10,
 'the': 11,
 'war': 12,
 'in': 13,
 'iraq': 14,
 'and': 15,
 'demand': 16,
 'withdrawal': 17,
 'british': 18,
 'troops': 19,
 'from': 20,
 'that': 21,
 'country': 22,
 '.': 23,
 'families': 24,
 'soldiers': 25,
 'killed': 26,
 'conflict': 27,
 'joined': 28,
 'protesters': 29,
 'who': 30,
 'carried': 31,
 'banners': 32,
 'with': 33,
 'such': 34,
 'slogans': 35,
 'as': 36,
 '"': 37,
 'bush': 38,
 'number': 39,
 'one': 40,
 'terrorist': 41,
 'stop': 42,
 'bombings': 43,
 'they': 44,
 'houses': 45,
 'parliament': 46,
 'a': 47,
 'rally': 48,
 'hyde': 49,
 'park': 50,
 'police': 51,
 'put': 52,
 'marchers': 53,
 'at': 54,
 '10,000': 55,
 'while': 56,
 'organizers': 57,
 'claimed': 58,
 'it': 59,
 'was': 60,
 '1,00,000': 61,
 'comes': 62,
 'on': 63,
 'eve': 64,
 'annual': 65,
 'conference': 66,
 'britain': 67,
 "'s": 68,
 'ruling': 69,
 'labor': 70,
 'party': 71,
 

In [ ]:
v['<unk>']=1

In [ ]:
x=[]
for i in l:
  p=i.split()
  k=[]
  for j in p:
    k.append(v[j])
  x.append(k)

In [ ]:
c=0
for i in x:
  if(len(i)>c):
    c=len(i)
print(c)

104


In [ ]:
xt=[]
for i in x:
  c=len(i)
  p=[0]*(104-c)
  p=i+p
  xt.append(p)

In [ ]:
d1={}
for i in d:
  p=i.lower()
  d1[p]=d[i]

In [ ]:
y=[]
for i in l1:
  p=i.split()
  k=[]
  for j in p:
    k.append(d1[j])
  y.append(k)

In [ ]:
yt=[]
for i in y:
  c=len(i)
  p=[0]*(104-c)
  p=i+p
  yt.append(p)

In [ ]:
len(yt[0])

104

In [ ]:
import numpy as np
yt1=np.array(yt)
xt1=np.array(xt)

In [ ]:
yt1.shape

(33570, 104)

In [ ]:
gl={}
with open('/content/contentgrive/MyDrive/glove.6B.50d.txt',encoding='utf8') as f:
    for i in f:
        c=i.split()
        word = c[0]
        coefs = np.asarray(c[1:],dtype='float32')
        gl[word] = coefs

In [ ]:
len(v)

27085

In [ ]:
vocab_size=len(v)+1
embedding_matrix = np.zeros((vocab_size, 50))
for word, i in v.items():
    k = gl.get(word)
    if k is not None:
        embedding_matrix[i] = k

In [ ]:
embedding_matrix[27085]

array([-0.54789001,  0.22273999,  0.43847999, -0.53195   , -0.56094003,
        0.76401001, -0.58942002,  0.58081001, -0.13298   ,  0.1587    ,
        0.28628001,  0.85623002,  0.53546   ,  1.21700001, -0.63268   ,
       -0.76012999, -0.046063  ,  0.22495   ,  0.37338999, -0.65147001,
       -0.089261  , -0.024264  , -0.50479001,  0.11448   ,  0.53966999,
        0.57941002,  0.12707999, -0.32556   , -0.17595001, -0.48427001,
        1.03129995,  0.15900999,  0.42317   , -0.38936001,  0.83341998,
        1.89820004,  1.16649997, -0.24913   , -0.46661001, -0.28455999,
        0.27177   ,  0.44957   , -0.93518001, -0.59386998, -0.60367   ,
       -0.74763   ,  0.42484   , -0.17470001, -0.22725999,  0.33063   ])

In [ ]:
len(d1)

17

In [ ]:
import tensorflow
from tensorflow.compat.v1.keras.layers import CuDNNLSTM

In [ ]:
from keras.models import Sequential
from keras.layers import Bidirectional,Embedding,Dense,LSTM
import keras
m=Sequential([
       Embedding(vocab_size,50,weights=[embedding_matrix],trainable=False,input_length=104),
       LSTM(64,return_sequences=True),
       Dense(18,activation='softmax')       
])
m.compile(optimizer=keras.optimizers.Adam(learning_rate=0.01),loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
m.fit(xt1,yt1,batch_size=64,epochs=5,verbose=2)

Epoch 1/5
525/525 - 33s - loss: 0.0829 - accuracy: 0.9808
Epoch 2/5
525/525 - 31s - loss: 0.0389 - accuracy: 0.9888
Epoch 3/5
525/525 - 31s - loss: 0.0348 - accuracy: 0.9897
Epoch 4/5
525/525 - 31s - loss: 0.0325 - accuracy: 0.9902
Epoch 5/5
525/525 - 31s - loss: 0.0310 - accuracy: 0.9905


In [ ]:
c=xt1[0]
c1=yt1[0]

In [ ]:
k=m.predict(np.array([c]))

In [ ]:
k.shape

(1, 104, 18)

In [ ]:
c1.shape

(104,)

In [ ]:
k1=np.argmax(k,axis=2)

In [ ]:
k1

array([[1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
c1

array([1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
m.save('Name recognition.h5')

In [ ]:
def preprocess(s):
  s=s.lower()
  p=s.split()
  ar=[]
  for i in p:
    if(i in v):
      ar.append(v[i])
    else:
      ar.append(v['<unk>'])
  arlen=len(ar)
  ar=ar+[0]*(104-arlen)
  return np.array(ar)

In [ ]:
c=preprocess("arun kumar and pawan is in england this monday")
k=m.predict(np.array([c]))
k=np.argmax(k,axis=2)

In [ ]:
k

array([[ 4,  4,  1,  4,  1,  1,  2,  1,  8, 13,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0]])

In [ ]:
d1

{'b-art': 9,
 'b-eve': 15,
 'b-geo': 2,
 'b-gpe': 3,
 'b-nat': 14,
 'b-org': 6,
 'b-per': 4,
 'b-tim': 8,
 'i-art': 10,
 'i-eve': 16,
 'i-geo': 5,
 'i-gpe': 12,
 'i-nat': 17,
 'i-org': 7,
 'i-per': 11,
 'i-tim': 13,
 'o': 1}